category_labels: Kategori
industry_labels: Industri
spesification_labels: Spesifikasi
comparison_labels: Perbandingan
product_not_found:
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: 'Maaf, produk yang Anda cari belum tersedia.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Sepertinya produk yang sedang Anda cari sudah tidak lagi tersedia di katalog kami, atau mungkin tautan yang Anda gunakan sudah kedaluwarsa.'
type_labels: 'Tipe Model'
model_labels: Model
dimention_labels: Dimensi
engine_labels: Engine
chassis_labels: Chassis
safety_security_labels: 'Safety & Security'
icon_accordion:
  - acc-product.svg
icon_accordion_active:
  - acc-product-active.svg
image_placeholders: placeholder.jpg
power: Power
torque: Torque
gvw: GVW
standard_emission: 'Standard Emission'
fuel_tank_capacity: 'Fuel Tank Capacity'
dump_dimensions: 'Dump Dimensions'
transmission: Transmission
brake_system: 'Brake System'
