category_labels: Kategori
industry_labels: Industri
spesification_labels: Spesifikasi
comparison_labels: Perbandingan
product_not_found:
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: 'Maaf, produk yang Anda cari belum tersedia.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Sepertinya produk yang sedang Anda cari sudah tidak lagi tersedia di katalog kami, atau mungkin tautan yang Anda gunakan sudah kedaluwarsa.'
benefit_label: 'Fitur dan Benefit'
type_labels: 'Tipe Model'
model_labels: Model
empty_placeholder_data: N/A
spesification_info:
  - power
  - torque
  - standard_emission
  - gcw
  - gvw
  - fuel_tank_capacity
image_placeholders: placeholder.jpg
image_features_benefit_placeholder:
  - placeholder.jpg
background_image_placeholder: bg-produk.jpg
background_pattern_image: pattern-single-product.png
