site_title: 'PT Gaya Makmur Mobil'
site_logo: gm-logo.png
favicon: favicon.png
social_media:
  instagram:
    url: 'https://instagram.com/gayamakmurmobil/'
    image: instagram.svg
  facebook:
    url: 'https://facebook.com/fawindonesia/'
    image: facebook.svg
  linkedin:
    url: 'https://linkedin.com/company/fawindonesia/'
    image: linkedin.svg
phone_numbers:
  -
    id: G53FNiaTI3Ir420dCazJR
    number: '+62 822-9999-9329'
    type: phone
    enabled: true
    label: 'GMM Care'
emails:
  -
    id: Jb3i9YhefDg5_pQomVBmv
    email: gmmcare@gmmobil.com
    type: email
    enabled: true
address: 'Jl. Lkr. Luar Barat No.9, RT.14/RW.3, Rw. Buaya, Kecamatan Cengkareng, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11740'
google_map_link: 'https://www.google.com/maps/place/PT.+Gaya+Makmur+Mobil+(FAW+Trucks+Indonesia)/@-6.1695975,106.7291991,19.96z/data=!4m6!3m5!1s0x2e69f785fb880fe7:0xfcd91397a84a0baa!8m2!3d-6.1696589!4d106.7290722!16s%2Fg%2F11bxdrrvwk!5m1!1e2?entry=ttu&g_ep=EgoyMDI2MDgxNi4wIKXMDSoASAFQAw%3D%3D'
custom_code_head: '<meta name="test-head" content="ok">'
custom_code_body: '<meta name="test-body" content="ok">'
google_analytics_measurement_id: G-YW01EDIMJ
header_desktop: true
header_mobile: true
show_scroll_top: true
scroll_top_position: left
translate_label: 'Pilih Bahasa'
embed_translate: |-
  <script>
    window.gtranslateSettings = {
    "default_language": "id",
    "languages": ["id", "en", ],
    "wrapper_selector": ".gtranslate_wrapper",
  }
  </script>
  <script src="https://cdn.gtranslate.net/widgets/latest/lc.js" defer></script>
icon: share-wa.svg
label_floating: 'Need Help? Chat with us'
heading: 'Start a Conversation'
short_description: 'Hi! Click one of our member below to chat on WhatsApp'
position: right
show_button: true
contact_whatsapp:
  -
    id: s451yKtL3eheMz2i5akU5
    title: 'GMM Customer WA Care'
    label: 'Pertanyaan Umum'
    message: 'Halo, Saya dapat informasi FAW dari Website gmmobil.com dan ingin menanyakan perihal produk FAW Trucks'
    nomor_whatsapp: 82299999329.0
    avatar: avatar.jpg
  -
    id: _YJgM4AwCFbQM7oH4jTWU
    nomor_whatsapp: 81112120563.0
    title: 'GMM Services Support'
    label: 'Pertanyaan Seputar Services FAW Trucks'
    avatar: avatar.jpg
  -
    id: ZaH7rQL5W7T0M3nSwMLD5
    title: 'GMM Parts Support'
    label: 'Pertanyaan Seputar Spare Parts FAW Trucks'
    nomor_whatsapp: 82298036789.0
    avatar: avatar.jpg
  -
    id: IjsovbTCd_jRU9Trf9Aya
    title: 'GMM Teletech Call & WA Center'
    label: 'Pertanyaan Seputar GMM Teletech Sistem'
    nomor_whatsapp: 81387777329.0
    avatar: avatar.jpg
