title: Kehutanan
content:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Perkembangan di sektor penebangan kayu baik dari Hutan Alam maupun Hutan Tanaman Industri yang makin tumbuh dengan cepat membutuhkan kendaraan angkut dengan kapasitas angkut yang maksimal, tenaga besar, handal dan efisien.'
updated_by: 28d34247-1c17-42bf-8548-5b36f18adcbd
updated_at: 1781854203
blueprint: industry
show: true
featured_image: industri-kehutanan.jpg
