title: Perkebunan
content:
  -
    type: paragraph
    content:
      -
        type: text
        text: "Jalan di perkebunan yang pada umumnya \_mempunyai kondisi dan medan yang berat\_ membutuhkan kendaraan yang mempunyai kecepatan dan kelincahan dalam pengangkutan Tandan Buah Segar serta dapat diandalkan dalam pengangkutan material\_yang diperlukan."
updated_by: 28d34247-1c17-42bf-8548-5b36f18adcbd
updated_at: 1781854297
blueprint: industry
featured_image: industri-perkebunan.jpg
show: true
