title: 'Product Label Information'
tabs:
  main:
    display: Main
    sections:
      -
        display: 'Archive Single Product'
        fields:
          -
            handle: category_labels
            field:
              type: text
              display: 'Category Labels'
              validate:
                - required
          -
            handle: industry_labels
            field:
              type: text
              display: 'Industry Labels'
              validate:
                - required
          -
            handle: spesification_labels
            field:
              type: text
              display: 'Spesification Labels'
              validate:
                - required
          -
            handle: comparison_labels
            field:
              type: text
              display: 'Comparison Labels'
              validate:
                - required
          -
            handle: product_not_found
            field:
              buttons:
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
              container: assets
              remove_empty_nodes: false
              type: bard
              display: 'Product Not Found'
              validate:
                - required
      -
        display: Comparison
        fields:
          -
            handle: type_labels
            field:
              type: text
              display: 'Type Labels'
              validate:
                - required
          -
            handle: model_labels
            field:
              type: text
              display: 'Model Labels'
              validate:
                - required
          -
            handle: dimention_labels
            field:
              type: text
              display: 'Dimention Labels'
          -
            handle: engine_labels
            field:
              type: text
              display: 'Engine Labels'
              validate:
                - required
          -
            handle: chassis_labels
            field:
              type: text
              display: 'Chassis Labels'
              validate:
                - required
          -
            handle: safety_security_labels
            field:
              type: text
              display: 'Safety & Security Labels'
              validate:
                - required
          -
            handle: icon_accordion
            field:
              container: assets
              type: assets
              display: 'Icon Accordion'
              width: 50
              validate:
                - required
          -
            handle: icon_accordion_active
            field:
              container: assets
              type: assets
              display: 'Icon Accordion Active'
              width: 50
              validate:
                - required
      -
        display: 'Skin Product'
        fields:
          -
            handle: image_placeholders
            field:
              container: assets
              max_files: 1
              type: assets
              display: 'Image Placeholders'
              validate:
                - required
      -
        display: Spesifikasi
        fields:
          -
            handle: power
            field:
              type: text
              display: Power
              width: 50
              validate:
                - required
          -
            handle: torque
            field:
              type: text
              display: Torque
              width: 50
              validate:
                - required
          -
            handle: gvw
            field:
              type: text
              display: GVW
              width: 50
          -
            handle: standard_emission
            field:
              type: text
              display: 'Standard Emission'
              width: 50
              validate:
                - required
          -
            handle: fuel_tank_capacity
            field:
              type: text
              display: 'Fuel Tank Capacity'
              width: 50
          -
            handle: dump_dimensions
            field:
              type: text
              display: 'Dump Dimensions'
              width: 50
              validate:
                - required
          -
            handle: transmission
            field:
              type: text
              display: Transmission
              width: 50
              validate:
                - required
          -
            handle: brake_system
            field:
              type: text
              display: 'Brake System'
              width: 50
              validate:
                - required
