title: 'Product Category'
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              display: Title
              localizable: true
              validate:
                - required
          -
            handle: images
            field:
              container: assets
              max_files: 1
              type: assets
              display: Images
              validate:
                - required
          -
            handle: content
            field:
              type: textarea
              display: Description
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              required: true
              validate:
                - required
                - 'max:200'
              localizable: true
          -
            handle: parent
            field:
              type: terms
              taxonomies:
                - product_categories
              max_items: 1
              display: 'Parent Category'
              localizable: true
  'SEO Meta':
    display: 'SEO Meta'
    sections:
      -
        fields:
          -
            handle: seo
            field:
              type: seo_pro
              listable: false
              display: SEO
  'SEO Previews':
    display: 'SEO Previews'
    sections:
      -
        fields:
          -
            handle: seo_previews
            field:
              type: seo_pro_previews
              listable: false
              display: 'SEO Previews'
              localizable: false
              hide_display: true
              unless:
                seo.enabled: 'equals false'
