title: 'Section settings'
fields:
  -
    handle: anchor
    field:
      type: text
      display: 'Anchor ID'
      instructions: 'Optional HTML id for in-page links (lowercase, no spaces).'
  -
    handle: show
    field:
      default: true
      type: toggle
      display: Show
      instructions: 'activate to reveal elements.'
