title: Products
icon: collections
template: products/show
layout: layout
taxonomies:
  - product_categories
  - industries
revisions: false
route: '/products/{slug}'
date: true
sort_by: date
sort_dir: desc
default_status: draft
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
