title: Products
icon: collections
template: products/show
layout: layout
taxonomies:
  - product_categories
  - industries
revisions: false
route: '/products/{slug}'
sort_by: date
sort_dir: desc
default_status: draft
date_behavior:
  past: null
  future: null
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
structure:
  root: false
