title: Product showcase
fields:
- handle: heading
  field:
    type: text
    display: Heading
    validate: required
    instructions: Judul bagian.
- handle: button
  field:
    type: group
    display: Section button
    fields:
    - import: common.button
    instructions: Tombol aksi.
- handle: products
  field:
    type: entries
    display: Products
    collections:
    - products
    validate: required
    instructions: Pilih produk.
