title: 'Dump Truck'
images: dump-truck.png
updated_by: 28d34247-1c17-42bf-8548-5b36f18adcbd
updated_at: 1782112933
blueprint: product_category
seo:
  title: '@seo:title'
  description: 'Jelajahi dump truck tambang, truk pasir, mobil truk besar dari FAW Trucks Indonesia untuk kebutuhan bisnis kalian semua.'
  image: '@seo:images'
