title: 'Lahat (Parts & Service)'
office_type: parts_service
dealer_category:
  - service-center
location:
  latitude: -3.786944
  longitude: 103.542778
updated_by: 28d34247-1c17-42bf-8548-5b36f18adcbd
updated_at: 1785386400
blueprint: location
