title: Morowali
office_type: parts_service
dealer_category:
  - parts-service-center
location:
  latitude: -2.5333
  longitude: 121.9667
updated_by: 28d34247-1c17-42bf-8548-5b36f18adcbd
updated_at: 1785386400
blueprint: location
