title: 'Semarang (Branch)'
office_type: branch
dealer_category:
  - cabang-dealer
location:
  latitude: -6.966667
  longitude: 110.416664
updated_by: 28d34247-1c17-42bf-8548-5b36f18adcbd
updated_at: 1785386400
blueprint: location
